name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    name: Snapshot
    runs-on: ubuntu-22.04

    steps:
      # -----------------------
      # Checkout repository
      # -----------------------
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # -----------------------
      # Configure git user
      # -----------------------
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # -----------------------
      # Remove docs folder if it exists
      # -----------------------
      - name: Remove docs folder
        run: |
          if [ -d "./docs" ]; then
            rm -rf ./docs
            echo "Folder './docs' removed."
          else
            echo "Folder './docs' does not exist. Skipping removal."
          fi

      # -----------------------
      # Prepare static folder
      # -----------------------
      - run: mkdir -p ~/static

      # -----------------------
      # Generate static HTML
      # -----------------------
      - name: Static HTML
        run: npx respec --localhost --src index.html --out ~/static/snapshot.html

      # -----------------------
      # Generate PDF
      # -----------------------
      #- name: Generate PDF
      #  run: |
      #    cp ~/static/snapshot.html snapshot.html
      #    npm i puppeteer
      #    python3 -m http.server 8080 &
      #    wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/pdf.js
      #    rm -f *.pdf
      #    node pdf.js      
      #    mv *.pdf ~/static/

      # -----------------------
      # Copy generated files to docs
      # -----------------------
      - name: Copy generated files to docs
        run: |
          mkdir -p ./docs
          cp -r ~/static/* ./docs/

      # -----------------------
      # Commit & push changes to temporary branch
      # -----------------------
      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b workflow/docs-update || git checkout workflow/docs-update
          git add ./docs
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Automatisch gegenereerde bestanden toegevoegd"
            git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git workflow/docs-update
          fi

      # -----------------------
      # Create Pull Request
      # -----------------------
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automatisch gegenereerde bestanden toegevoegd"
          branch: workflow/docs-update
          base: main
          title: "Update docs"
          body: "Automatisch gegenereerde bestanden via GitHub Actions."
          draft: false

      # -----------------------
      # Enable auto-merge
      # -----------------------
      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
